
USE hr;

-- Drop all temporary databases if exists
DROP TEMPORARY TABLE IF EXISTS temp_region;
DROP TEMPORARY TABLE IF EXISTS temp_pays;
DROP TEMPORARY TABLE IF EXISTS temp_bureau;
DROP TEMPORARY TABLE IF EXISTS temp_employe;
DROP TEMPORARY TABLE IF EXISTS temp_departement;
DROP TEMPORARY TABLE IF EXISTS temp_emploi;
DROP TEMPORARY TABLE IF EXISTS temp_historique_emploi;


-- Fait par Mélissa, Françis et Yani.
CREATE TEMPORARY TABLE IF NOT EXISTS temp_region (
    ID_REGION INT(11) NOT NULL,
    NOM_REGION VARCHAR(30) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_pays (
    ID_PAYS VARCHAR(3) NOT NULL,
    NOM_PAYS VARCHAR(30) NOT NULL,
    ID_REGION INT(11) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_bureau (
    ID_BUREAU INT(11) NOT NULL,
    ADRESSE_RUE_BUREAU VARCHAR(30) NOT NULL,
    CODE_POSTAL_BUREAU VARCHAR(12) NOT NULL,
    NOM_VILLE_BUREAU VARCHAR(60) NOT NULL,
    COURRIEL_BUREAU VARCHAR(60) NOT NULL,
    ID_PAYS VARCHAR(3) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_employe (
    ID_EMPLOYE INT(11) NOT NULL,
    PRENOM_EMPLOYE VARCHAR(30) NOT NULL,
    NOM_EMPLOYE VARCHAR(30) NOT NULL,
    COURRIEL_EMPLOYE VARCHAR(60) NOT NULL,
    ADRESSE_RUE_EMPLOYE VARCHAR(60),
    ADRESSE_VILLE_EMPLOYE VARCHAR(60),
    ADRESSE_CP_EMPLOYE VARCHAR(12),
    RESPONSABLE_EMPLOYE INT(11)
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_departement (
    ID_DEPARTEMENT INT(11) NOT NULL,
    NOM_DEPARTEMENT VARCHAR(30) NOT NULL,
    DIRECTEUR_DEPARTEMENT INT(11),
    ID_BUREAU INT(11) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_emploi (
    ID_EMPLOI VARCHAR(10) NOT NULL,
    TITRE_EMPLOI VARCHAR(60) NOT NULL,
    SALAIRE_MINIMUM DECIMAL(10,2) NOT NULL,
    SALAIRE_MAXIMUM DECIMAL(10,2) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS temp_historique_emploi (
    ID_EMPLOYE INT(11) NOT NULL,
    ID_EMPLOI VARCHAR(10) NOT NULL,
    DATE_DEBUT_EMPLOI DATETIME NOT NULL,
    DATE_FIN_EMPLOI DATETIME,
    ID_DEPARTEMENT INT(11) NOT NULL,
    SALAIRE DECIMAL(10,2) NOT NULL
);

-- Load data from CSV files into temporary tables
LOAD DATA INFILE './tmp/REGIONS.csv'
INTO TABLE temp_region
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_REGION, NOM_REGION);

LOAD DATA INFILE './tmp/PAYS.csv'
INTO TABLE temp_pays
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_PAYS,NOM_PAYS,ID_REGION);

LOAD DATA INFILE './tmp/BUREAUX.csv'
INTO TABLE temp_bureau
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_BUREAU,ID_PAYS,ADRESSE_RUE_BUREAU,CODE_POSTAL_BUREAU,NOM_VILLE_BUREAU,COURRIEL_BUREAU);

LOAD DATA INFILE './tmp/EMPLOYES.csv'
INTO TABLE temp_employe
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_EMPLOYE,RESPONSABLE_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,COURRIEL_EMPLOYE,ADRESSE_RUE_EMPLOYE,ADRESSE_VILLE_EMPLOYE,ADRESSE_CP_EMPLOYE);

LOAD DATA INFILE './tmp/DEPARTEMENTS.csv'
INTO TABLE temp_departement
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_DEPARTEMENT,NOM_DEPARTEMENT,DIRECTEUR_DEPARTEMENT,ID_BUREAU);

LOAD DATA INFILE './tmp/EMPLOIS.csv'
INTO TABLE temp_emploi
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_EMPLOI,TITRE_EMPLOI,SALAIRE_MINIMUM,SALAIRE_MAXIMUM);

LOAD DATA INFILE './tmp/HISTORIQUE_EMPLOIS.csv'
INTO TABLE temp_historique_emploi
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID_EMPLOYE,DATE_DEBUT_EMPLOI,DATE_FIN_EMPLOI,ID_EMPLOI,ID_DEPARTEMENT,SALAIRE);



INSERT INTO region (SELECT * FROM temp_region);
INSERT INTO pays SELECT * FROM temp_pays;
INSERT INTO bureau (SELECT * FROM temp_bureau);
INSERT INTO employe SELECT * FROM temp_employe;
INSERT INTO departement SELECT * FROM temp_departement;
INSERT INTO emploi SELECT * FROM temp_emploi;
INSERT INTO historique_emploi SELECT * FROM temp_historique_emploi;

COMMIT;

DROP TEMPORARY TABLE temp_region;
DROP TEMPORARY TABLE temp_pays;
DROP TEMPORARY TABLE temp_bureau;
DROP TEMPORARY TABLE temp_employe;
DROP TEMPORARY TABLE temp_departement;
DROP TEMPORARY TABLE temp_emploi;
DROP TEMPORARY TABLE temp_historique_emploi;

SELECT 'Data inserted successfully.';