DROP DATABASE IF EXISTS hr;
CREATE DATABASE hr;
USE hr;

# Créer les tables
CREATE TABLE IF NOT EXISTS `employe` (
  `ID_EMPLOYE` int(11) NOT NULL AUTO_INCREMENT,
  `PRENOM_EMPLOYE` varchar(20) DEFAULT NULL,
  `NOM_EMPLOYE` varchar(25) NOT NULL,
  PRIMARY KEY (`ID_EMPLOYE`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
# Créer les contraintes

