DROP DATABASE IF EXISTS hr;
CREATE DATABASE hr;
USE hr;


CREATE TABLE employe (
    ID_EMPLOYE INT(11) NOT NULL AUTO_INCREMENT,,
    PRENOM_EMPLOYE VARCHAR(30) NOT NULL,
    NOM_EMPLOYE VARCHAR(30) NOT NULL,
    COURRIEL_EMPLOYE VARCHAR(60) NOT NULL,
    ADRESSE_RUE_EMPLOYE VARCHAR(60),
    ADRESSE_VILLE_EMPLOYE VARCHAR(60),
    ADRESSE_CP_EMPLOYE VARCHAR(12),
    RESPONSABLE_EMPLOYE INT(11),
    PRIMARY KEY (ID_EMPLOYE),
    FOREIGN KEY (RESPONSABLE_EMPLOYE) REFERENCES employe(ID_EMPLOYE)
);

CREATE TABLE bureau (
    ID_BUREAU INT(11) NOT NULL AUTO_INCREMENT,
    ADRESSE_RUE_BUREAU VARCHAR(30) NOT NULL,
    CODE_POSTAL_BUREAU VARCHAR(12) NOT NULL,
    NOM_VILLE_BUREAU VARCHAR(60) NOT NULL,
    COURRIEL_BUREAU VARCHAR(60) NOT NULL,
    ID_PAYS VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID_BUREAU),
    FOREIGN KEY (ID_PAYS) REFERENCES pays(ID_PAYS)
);

-- Creer la table historique_emploi
-- ID_EMPLOYE INT(11)
-- ID_EMPLOI VARCHAR(10)
-- DATE_DEBUT_EMPLOI DATETIME (primary key)
-- DATE_FIN_EMPLOI DATETIME
-- ID_DEPARTEMENT INT(11) (Clé étrangère)
-- SALAIRE DECIMAL(10,2) (Champs)

CREATE TABLE historique_emploi (
    ID_EMPLOYE INT(11) NOT NULL,
    ID_EMPLOI VARCHAR(10) NOT NULL,
    DATE_DEBUT_EMPLOI DATETIME NOT NULL,
    DATE_FIN_EMPLOI DATETIME,
    ID_DEPARTEMENT INT(11) NOT NULL,
    SALAIRE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_EMPLOYE, DATE_DEBUT_EMPLOI),
    FOREIGN KEY (ID_EMPLOYE) REFERENCES employe(ID_EMPLOYE),
    FOREIGN KEY (ID_DEPARTEMENT) REFERENCES departement(ID_DEPARTEMENT)
);


-- Creer la table departement
-- ID_DEPARTEMENT INT(11) 
-- NOM_DEPARTEMENT VARCHAR(30)
--DIRECTEUR_DEPARTEMENT INT(11)
-- ID_BUREAU INT(11)
CREATE TABLE departement (
    ID_DEPARTEMENT INT(11) NOT NULL AUTO_INCREMENT,
    NOM_DEPARTEMENT VARCHAR(30) NOT NULL,
    DIRECTEUR_DEPARTEMENT INT(11),
    ID_BUREAU INT(11) NOT NULL,
    PRIMARY KEY (ID_DEPARTEMENT),
    FOREIGN KEY (DIRECTEUR_DEPARTEMENT) REFERENCES employe(ID_EMPLOYE),
    FOREIGN KEY (ID_BUREAU) REFERENCES bureau(ID_BUREAU)
);

-- Creer la table emploi
-- ID_EMPLOI VARCHAR(10)
--TITRE_EMPLOI VARCHAR(60)
--SALAIRE_MINiMUM DECIMAL(10,2)
--SALAIRE_MAXIMUM DECIMAL(10,2)
CREATE TABLE emploi (
    ID_EMPLOI VARCHAR(10) NOT NULL,
    TITRE_EMPLOI VARCHAR(60) NOT NULL,
    SALAIRE_MINIMUM DECIMAL(10,2) NOT NULL,
    SALAIRE_MAXIMUM DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_EMPLOI)
);

-- Creer la table pays
-- ID_PAYS VARCHAR(3) (Clé primaire)
-- NOM_PAYS VARCHAR(30) (Champs)
-- ID_REGION INT(11) (Clé étrangère)

CREATE TABLE pays (
    ID_PAYS VARCHAR(3) NOT NULL,
    NOM_PAYS VARCHAR(30) NOT NULL,
    ID_REGION INT(11) NOT NULL,
    PRIMARY KEY (ID_PAYS),
    FOREIGN KEY (ID_REGION) REFERENCES region(ID_REGION)
);

-- Creer la table region
-- ID_REGION INT(11) (Clé primaire)
-- NOM_REGION VARCHAR(30) (Champs)
CREATE TABLE region (
    ID_REGION INT(11) NOT NULL,
    NOM_REGION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_REGION)
);