-- Fait par Mélissa, Françis et Yani.
DROP DATABASE IF EXISTS hr;
CREATE DATABASE hr;
USE hr;

CREATE TABLE employe (
    ID_EMPLOYE INT(11) NOT NULL AUTO_INCREMENT,
    PRENOM_EMPLOYE VARCHAR(30) NOT NULL,
    NOM_EMPLOYE VARCHAR(30) NOT NULL,
    COURRIEL_EMPLOYE VARCHAR(60) NOT NULL,
    ADRESSE_RUE_EMPLOYE VARCHAR(60),
    ADRESSE_VILLE_EMPLOYE VARCHAR(60),
    ADRESSE_CP_EMPLOYE VARCHAR(12),
    RESPONSABLE_EMPLOYE INT(11),
    PRIMARY KEY (ID_EMPLOYE),
    FOREIGN KEY (RESPONSABLE_EMPLOYE) REFERENCES employe(ID_EMPLOYE)
);

CREATE TABLE region (
    ID_REGION INT(11) NOT NULL,
    NOM_REGION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_REGION)
);

CREATE TABLE pays (
    ID_PAYS VARCHAR(3) NOT NULL,
    NOM_PAYS VARCHAR(30) NOT NULL,
    ID_REGION INT(11) NOT NULL,
    PRIMARY KEY (ID_PAYS),
    FOREIGN KEY (ID_REGION) REFERENCES region(ID_REGION)
);

CREATE TABLE bureau (
    ID_BUREAU INT(11) NOT NULL AUTO_INCREMENT,
    ADRESSE_RUE_BUREAU VARCHAR(30) NOT NULL,
    CODE_POSTAL_BUREAU VARCHAR(12) NOT NULL,
    NOM_VILLE_BUREAU VARCHAR(60) NOT NULL,
    COURRIEL_BUREAU VARCHAR(60) NOT NULL,
    ID_PAYS VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID_BUREAU),
    FOREIGN KEY (ID_PAYS) REFERENCES pays(ID_PAYS)
); 

CREATE TABLE departement (
    ID_DEPARTEMENT INT(11) NOT NULL AUTO_INCREMENT,
    NOM_DEPARTEMENT VARCHAR(30) NOT NULL,
    DIRECTEUR_DEPARTEMENT INT(11),
    ID_BUREAU INT(11) NOT NULL,
    PRIMARY KEY (ID_DEPARTEMENT),
    FOREIGN KEY (DIRECTEUR_DEPARTEMENT) REFERENCES employe(ID_EMPLOYE),
    FOREIGN KEY (ID_BUREAU) REFERENCES bureau(ID_BUREAU)
);

CREATE TABLE historique_emploi (
    ID_EMPLOYE INT(11) NOT NULL,
    ID_EMPLOI VARCHAR(10) NOT NULL,
    DATE_DEBUT_EMPLOI DATETIME NOT NULL,
    DATE_FIN_EMPLOI DATETIME DEFAULT (DATE_ADD(NOW(), INTERVAL 10 YEAR)),
    CHECK (DATE_FIN_EMPLOI > DATE_DEBUT_EMPLOI OR DATE_FIN_EMPLOI IS NULL),
    ID_DEPARTEMENT INT(11) NOT NULL,
    SALAIRE DECIMAL(10,2) NOT NULL DEFAULT 100.00,
    PRIMARY KEY (ID_EMPLOYE, ID_EMPLOI, DATE_DEBUT_EMPLOI),
    FOREIGN KEY (ID_EMPLOYE) REFERENCES employe(ID_EMPLOYE),
    FOREIGN KEY (ID_DEPARTEMENT) REFERENCES departement(ID_DEPARTEMENT),
    CHECK (DATE_DEBUT_EMPLOI < DATE_FIN_EMPLOI)
);


CREATE TABLE emploi (
    ID_EMPLOI VARCHAR(10) NOT NULL,
    TITRE_EMPLOI VARCHAR(60) NOT NULL,
    SALAIRE_MINIMUM DECIMAL(10,2) NOT NULL DEFAULT 100.00 CHECK (SALAIRE_MINIMUM BETWEEN 100 AND 100000),
    SALAIRE_MAXIMUM DECIMAL(10,2) NOT NULL CHECK (SALAIRE_MAXIMUM BETWEEN 250 AND 250000),
    PRIMARY KEY (ID_EMPLOI),
    CHECK (SALAIRE_MINIMUM < SALAIRE_MAXIMUM)
);


