USE hr;

-- Load data from CSV files into temporary tables
LOAD DATA INFILE './tmp/REGIONS.csv' INTO TABLE region FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/PAYS.csv' INTO TABLE pays FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/BUREAUX.csv' INTO TABLE bureau FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/EMPLOYE.csv' INTO TABLE employe FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/DEPARTEMENT.csv' INTO TABLE departement FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/EMPLOI.csv' INTO TABLE emploi FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE './tmp/HISTORIQUE_EMPLOI.csv' INTO TABLE historique_emploi FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 LINES;
COMMIT;

SELECT 'Data inserted successfully.';